name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - run: make setup-ci-env
      - run: make validate-ci
      - run: make validate
      - run: make build
      - name: Test
        run: |
          make test